import blockNames

class SIMULATION_TYPE:
    PELE, MD, TEST = range(3)

SIMULATION_TYPE_TO_STRING_DICTIONARY = {
    SIMULATION_TYPE.PELE:blockNames.SIMULATION_TYPE.PELE,
    SIMULATION_TYPE.MD:blockNames.SIMULATION_TYPE.MD,
    SIMULATION_TYPE.TEST:blockNames.SIMULATION_TYPE.TEST
}
