FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
LABEL maintainer="cescgina@gmail.com"

RUN apt-get update \
    && apt-get install wget -y \
    && apt-get clean

# Install conda and check the md5 sum provided on the download
# site
ENV MINICONDA_VERSION=4.8.2 \
    MINICONDA_MD5=87e77f097f6ebb5127c77662dfc3165e \
    CONDA_VERSION=4.8.2 \
	CONDA_DIR=/opt/conda \
    PATH=/opt/conda/bin:$PATH

RUN cd /tmp && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-py37_${MINICONDA_VERSION}-Linux-x86_64.sh && \
    echo "${MINICONDA_MD5} *Miniconda3-py37_${MINICONDA_VERSION}-Linux-x86_64.sh" | md5sum -c - && \
    /bin/bash Miniconda3-py37_${MINICONDA_VERSION}-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Miniconda3-py37_${MINICONDA_VERSION}-Linux-x86_64.sh && \
    echo "conda ${CONDA_VERSION}" >> $CONDA_DIR/conda-meta/pinned && \
    conda config --system --prepend channels conda-forge && \
    conda config --system --prepend channels omnia && \
    conda config --system --set auto_update_conda false && \
    conda config --system --set show_channel_urls true && \
    conda config --system --set channel_priority strict && \
    conda list python | grep '^python ' | tr -s ' ' | cut -d '.' -f 1,2 | sed 's/$/.*/' >> $CONDA_DIR/conda-meta/pinned && \
    conda install --quiet --yes conda && \
    conda install --quiet --yes pip && \
    conda update --all --quiet --yes && \
    conda clean --all -f -y

WORKDIR /AdaptivePELE

COPY requirements.txt /AdaptivePELE

RUN conda install --yes openmm=7.4.1
RUN pip install --no-cache-dir --requirement requirements.txt

COPY . /AdaptivePELE

RUN python setup.py install

RUN cd .. && rm -r AdaptivePELE

WORKDIR /work
